#!/bin/sh -e

set -e

jdk_tools='appletviewer jconsole'
basedir=/usr/lib/jvm/java-8-openjdk-amd64


if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    for i in $jdk_tools; do
	update-alternatives --remove $i $basedir/bin/$i
    done
fi


