#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove futurize /usr/bin/python2-futurize
	update-alternatives --remove pasteurize /usr/bin/python2-pasteurize
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-future 
else
	dpkg -L python-future | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
